function [ skinnys ] = skinnyTriangles( TRI, V, alpha )
%SKINNYTRIANGLES Summary of this function goes here
%   Detailed explanation goes here
    x = V(1,:)';
    y = V(2,:)';
    X = x(TRI);
    Y = y(TRI);
    a=zeros(size(X));
    for cnt=1:3
        a(:,cnt) = abs( ...
            diff( ...
                angle( ...
                    bsxfun( @minus, X(:,[1:cnt-1 cnt+1:end]), X(:,cnt) )...
                  + 1i ...
                  * bsxfun( @minus, Y(:,[1:cnt-1 cnt+1:end]), Y(:,cnt) )...
                ),[],2 ...
            ) ...
        );
    end
end

